### PR TITLE
Scaling

### PR DESCRIPTION
**Pull request by VeoWulfOfWallSt**
Scaling resolution fix

### CODE REVIEW

**Review by abdrdg — APPROVED** [review]
Still need to fix the stretching issue. Some issues will be closed with this PR finally.  
OK

**Review by Syoraka — APPROVED** [review]
Approved. Scaling/Stretch issue still persist on some but resolutions but definitely playable.

**Review by johnzillakaiju — COMMENTED** [review]
Veo is too good! scaling approve!

**Review by johnzillakaiju — APPROVED** [review]
Approve!

**Pull request merged**
