### PR TITLE
Added new dog asset with blinking animation and new heart assets

### LINKED ISSUE #27: [Feature Request] Add a random blinking animation when the dog is running in the Agility Scene
# [Request] Dog randomly blinking while running in the Agility Scene
Description:
The request came from the Art team. They wanted the dog to look more natural and realistic by having a random blinking animation.
Here is the expected animation but the eye blinks on a random chance: 
Anim-Recovered-JD (2)

### PR DESCRIPTION
**Pull request by johnzillakaiju**
Dog is now blinking and updated the heart prefab with new sprite

### CODE REVIEW

**Review by abdrdg — DISMISSED** [review]
Please resolve scene conflicts within the Agility scene first. Thank you! 😊 @johnzillakaiju

**Review by abdrdg — APPROVED** [review]
Looks good (y)

**Review by khmflrdlz — APPROVED** [review]
The Heart Asset and the blinking animation render properly. Pull request approve!

**Review by Syoraka — APPROVED** [review]
Pull request approved!

**Pull request merged**
