### PR TITLE
Feeding fix issue#42

### PR DESCRIPTION
**Pull request by Syoraka**
- Changes to Hieracrhy
- Adjusted the amount of food falling
- Adjusted the speed of falling food
- Adjusted the box collision of foods and dog bowl
- UI Layout changes
- Added a placeholder font
- Button asset implemented

### CODE REVIEW

**Review by abdrdg — CHANGES_REQUESTED** [review]
**Issues found:**
1. Playing on some resolutions makes the dog, background, and food assets invisible. 
2. Food still spawns one at a time.

**Review by khmflrdlz — CHANGES_REQUESTED** [review]
same issue was found on my end.

The reference is attached.
image

**Review by LexxTheSixth — CHANGES_REQUESTED** [review]
First issue happens to me on 18:9 aspect ratio

**Review by khmflrdlz — APPROVED** [review]
Pull Request Approved. The amount of food is fantastic!

**Review by abdrdg — APPROVED** [review]
Nice. Food spawns as intended. Scaling issue will be fixed by @VeoWulfOfWallSt next sprint.

**Review by LexxTheSixth — APPROVED** [review]
No issues found.

**Pull request merged**
