### PR TITLE
Pause Menu Feature

### PR DESCRIPTION
**Pull request by khmflrdlz**
• created a pause function in Agility Scene
• created a pause menu when you click the pause function
• pause and menu button in the pause menu

### CODE REVIEW

**Comment by abdrdg** [comment]
@Syoraka @carebeardrew Requesting reviews. Pause menu should be in the Agility Scene.

**Review by carebeardrew — CHANGES_REQUESTED** [review]
There is no resume button

**Review by Syoraka — CHANGES_REQUESTED** [review]
• Pause Menu UI elements are not visible after pressing the Pause Button
• Pause Menu UI elements does not disappear after pressing the Resume Button

**Review by abdrdg — CHANGES_REQUESTED** [review]
Seems like there are issues. Requesting changes.

**Comment by khmflrdlz** [comment]
• Pause Menu UI elements are not visible after pressing the Pause Button
• Pause Menu UI elements do not disappear after pressing the Resume Button

**Pause Menu Fix has been done**

@abdrdg @Syoraka @carebeardrew 
kindly check if the issues are fixed on your end. Thank you, guys!

**Review by abdrdg — APPROVED** [review]

**Review by carebeardrew — APPROVED** [review]
Ok :D

**Review by Syoraka — CHANGES_REQUESTED** [review]
UI Elements does not automatically resize on different resolution and appears misaligned on the screen. 

image

**Comment by khmflrdlz** [comment]
@Syoraka I have pushed the fix of UI in GitHub. Could you please verify the status of the fix? Thank you.

**Review by Syoraka — APPROVED** [review]

**Pull request merged**
