### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by carebeardrew**
Fixed 3 issues 
- [Visual] [The food asset is not removed on screen when finishing the Feeding Mini game]
- [Gameplay] [The Hit Points does not decrease when colliding with the topmost part of obstacle in Agility mini game] 
- [Functionality][Dev] Pause button still functions after completing the Agility minigame

### CODE REVIEW

**Comment by abdrdg** [comment]
- [x] [Visual] [The food asset is not removed on screen when finishing the Feeding Mini game] 
- [x] [Gameplay] [The Hit Points does not decrease when colliding with the topmost part of obstacle in Agility mini game] 
- [x] [Functionality][Dev] Pause button still functions after completing the Agility minigame

**Review by abdrdg — APPROVED** [review]
Noice. Issue fixed

**Review by VeoWulfOfWallSt — APPROVED** [review]
Push Button Approved

**Review by khmflrdlz — APPROVED** [review]
Pull Request Approved. All issues are fixed.

**Pull request merged**
