### PR TITLE
Grooming

### PR DESCRIPTION
**Pull request by johnzillakaiju**
grooming to dev

### CODE REVIEW

**Review by LexxTheSixth — APPROVED** [review]
No issues found.

**Review by khmflrdlz — APPROVED** [review]
No issues were found. Pull request approved.

**Review by abdrdg — CHANGES_REQUESTED** [review]
No apparent issues. Lacking assets for sure lol. 
Can we have the button in the minigames menu functional so we can access the grooming scene from there.

**Comment by VeoWulfOfWallSt** [comment]
> No apparent issues. Lacking assets for sure lol. Can we have the button in the minigames menu functional so we can access the grooming scene from there.

Finished this request, Clicking Grooming button leads to the correct scene  now

**Review by abdrdg — APPROVED** [review]

**Comment by abdrdg** [comment]
Hi! Let's make this more polished muna before we merge it to dev. 👍 Closing pull request

**Pull request closed without merging**
